---
product-name: control-plane
network-properties:
  network:
    name: {{.control_plane_subnet_name}}
  other_availability_zones:
    {{range .azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index .azs 0}}
product-properties:
  .properties.domain:
    value: {{.control_plane_domain}}
resource-config:
  worker:
    internet_connected: true
  db:
    internet_connected: false
  web:
    elb_names:
    - tcp:{{.control_plane_lb_name}}
    internet_connected: false
  uaa:
    elb_names:
    - tcp:{{.control_plane_uaa_lb_name}}
    internet_connected: false
  credhub:
    elb_names:
    - tcp:{{.control_plane_credhub_lb_name}}
    internet_connected: false
